spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234567
      jdbc-url: jdbc:mysql://localhost:3306/main?useUnicode=true
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234567
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true

server:
  port: 8090