server:
  port: 9091

spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql:///test?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver

pagehelper:
  auto-dialect: mysql
  reasonable: true # ????????pageNum <= 0 ??????pageNum > ????????
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
